name: Check Labs Directory

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  check_labs_directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check file types
        run: |
          # Find and list files under Labs\ that are not .java, .txt, or .pdf
          invalid_files=$(find Labs/ -type f ! \( -name '*.java' -o -name '*.txt' -o -name '*.pdf' \))
          # Print the names of invalid files
          echo "$invalid_files"
          # Store the exit code in a variable
          exit_code=$?
          # Exit with an error code if any non .java, .txt, or .pdf files are found
          if [ $exit_code -eq 0 ]; then
            echo "Error: Found files other than .java, .txt, or .pdf under Labs\ directory."
            exit 1
          fi
